<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/12
 * Time: 22:31
 */


namespace app\index\controller;

use app\common\controller\Frontend;
use think\Lang;
use think\Db;
use QL\QueryList;

/**
 * Ajax异步请求接口
 * @internal
 */
class Caiji
{
    private $parent_id = 0;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function meet(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/rql/';
        $data = [];
        //猪肉分类
        $data['zhurou'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //牛肉分类
        $data['niurou'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //鸡肉分类
        $data['jirou'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //羊肉分类
        $data['yangrou'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //蛋类
        $data['yangrou'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其它肉类
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');
        //其它禽类
        $data['other_qinlei'] = QueryList::get($url)->find('div.category_sub:nth-child(7) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function shuichanpin(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/scl/';
        $data = [];
        //淡水鱼
        $data['danshuiyu'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //海水鱼
        $data['haishuiyu'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //虾类
        $data['xia'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //蟹类
        $data['xie'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //贝类
        $data['bei'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其他水产类
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function shucai(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/shucailei/';
        $data = [];
        //茎叶类
        $data['jingye'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //瓜菜类
        $data['guacai'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //果实类
        $data['guoshi'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //根茎类
        $data['genjing'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //菌类
        $data['jun'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其他
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function guopin(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/guopinlei/';
        $data = [];
        //鲜果类
        $data['xianguo'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //干果类
        $data['ganguo'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function mimian(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/mmdr/';
        $data = [];
        //米类
        $data['mi'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //面类
        $data['mian'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //豆类
        $data['dou'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //豆制品
        $data['douzhipin'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //乳类
        $data['ru'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //方便食品类
        $data['fangbian'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function tiaoweipin(){
        $url = 'https://www.meishichina.com/YuanLiao/category/tiaoweipinl/';
        $data = [];
        //调味品
        $data['tiaoweipin'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //食用油
        $data['shiyongyou'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function yaoshi(){
        $url = 'https://www.meishichina.com/YuanLiao/category/yaoshiqita/';
        $data = [];
        //药食
        $data['tiaoweipin'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('shicai_category')->insert($temp);
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function food_category(){
        $url = 'https://home.meishichina.com/recipe-type.html';
        $data = [];
        //常见菜式
        $data['jiachangcai'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //主食/小吃
        $data['xiaochi'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //甜品/饮品
        $data['tianpin'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //适宜人群
        $data['tianpin'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //食疗食补
        $data['shibu'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //场景
        $data['changjing'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');
        //饮食方式
        $data['yingshi'] = QueryList::get($url)->find('div.category_sub:nth-child(7) > ul > li > a')->attrs('title');
        //中式菜式
        $data['china'] = QueryList::get($url)->find('div.category_sub:nth-child(8) > ul > li > a')->attrs('title');
        //外国美食
        $data['world'] = QueryList::get($url)->find('div.category_sub:nth-child(9) > ul > li > a')->attrs('title');
        //烘焙
        $data['hongpei'] = QueryList::get($url)->find('div.category_sub:nth-child(10) > ul > li > a')->attrs('title');
        //传统美食
        $data['chuantong'] = QueryList::get($url)->find('div.category_sub:nth-child(11) > ul > li > a')->attrs('title');
        //节日食俗
        $data['jieri'] = QueryList::get($url)->find('div.category_sub:nth-child(12) > ul > li > a')->attrs('title');
        //按制作难度
        $data['hard'] = QueryList::get($url)->find('div.category_sub:nth-child(13) > ul > li > a')->attrs('html');
//        var_dump($data);exit;
        //按所需时间
        $data['time'] = QueryList::get($url)->find('div.category_sub:nth-child(14) > ul > li > a')->attrs('text');
        //按菜品口味
        $data['kouwei'] = QueryList::get($url)->find('div.category_sub:nth-child(15) > ul > li > a')->attrs('text');
        //按主要工艺
        $data['gongyi'] = QueryList::get($url)->find('div.category_sub:nth-child(16) > ul > li > a')->attrs('text');

        $url = file_get_contents('https://home.meishichina.com/recipe-type.html');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $temp['parent_id'] = 0;
                    $temp['food_category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('food_category')->insert($temp);
                    if ($res){
                        $this->parent_id = db::name('food_category')->getLastInsID();
                    }
                }else{
                    $temp['parent_id'] = $this->parent_id;
                    $temp['food_category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    $res = db::name('food_category')->insert($temp);
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }


    public function recai(){
        $url = file_get_contents('https://home.meishichina.com/recipe/recai/');

        $ql = QueryList::rules(array(
            'food_name' => array('#J_list >ul > li >.detail > h2>a','text'),
            'food_url' => array('#J_list >ul > li >.detail > h2>a','href'),
            'tags' => array('#J_list >ul > li >.detail > p.subcontent','text'),
            'images' => array('#J_list > ul > li > div.pic > a > img','data-src'),
            'author_name' => array('#J_list > ul > li > div.detail > p.subline > a','text'),
//            'author_url' => array('#J_list > ul > li > div.detail > p.subline > a','href'),
            'page' => array('.ui-page-inner .now_page','text'),
        ));
        $data = $ql->setHtml($url)->removeHead()->query()->getData();
        var_dump($data);
        Db::startTrans();
        foreach($data as $key => $value){
            if ($key == 0){
                unset($value['page']);
            }
            $value['create_time'] = $value['update_time'] = date('Y-m-d H:i:s');
            $value['images'] = explode('?',$value['images'])[0];
            $res = db::name('food_list')->insert($value);
            echo db::name('food_list')->getLastSql();
            if (!$res){
                DB::rollback();
            }else{
                $html = file_get_contents($value['food_url']);
                $food = QueryList::rules(array(
                    'title' => array('#recipe_title','text'),
                    'top_image' => array('#recipe_De_imgBox > a > img','src'),
                    'tag1' => array('div.recipeCategory_sub_R.clear','html'),
                    'tag3' => array('body > div.wrap > div > div.space_left > div.space_box_home > div > fieldset > div > ul','html'),
                    'tag2' => array('div.recipeCategory_sub_R.mt30.clear','html'),
                ));
                $data = $food->setHtml($html)->removeHead()->query()->getData();
                echo '<pre>';
//                var_dump($data);exit;
                preg_match_all('/<b>(.+?)<\/b>/', $data[0]['tag1'], $tag1);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[0]['tag1'], $tag2);

                str_replace('<b>','',$tag1[1]);
                str_replace('</b>','',$tag1[1]);

                $table1 = array_combine($tag1[1],$tag2[1]);
//                var_dump($data[0]['tag2']);
                preg_match_all('/target="_blank">(.+?)<\/a>/', $data[0]['tag2'], $tag3);
//                var_dump($tag3);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[0]['tag2'], $tag4);

                str_replace('<b>','',$tag3[1]);
                str_replace('</b>','',$tag3[1]);

                $table2 = array_combine($tag3[1],$tag4[1]);

                preg_match_all('/<b>(.+?)<\/b>/', $data[1]['tag3'], $tag33);
//                var_dump($tag33);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[1]['tag3'], $tag44);
//                var_dump($tag44);exit;

                str_replace('<b>','',$tag33[1]);
                str_replace('</b>','',$tag33[1]);

                $table3 = array_combine($tag33[1],$tag44[1]);

                print_r($table1);
                print_r($table2);
                print_r($table3);
                exit;
            }
        }
    }
}