<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/12
 * Time: 22:31
 */


namespace app\index\controller;

use app\common\controller\Frontend;
use think\Lang;
use think\db;
use QL\QueryList;

/**
 * Ajax异步请求接口
 * @internal
 */
class Caiji
{
    private $url = '';
    private $rule = array();
    private $bigCategory = '';
    private $smallCategory = array();


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        //采集某页面所有的图片
        $data = QueryList::get('http://cms.querylist.cc/bizhi/453.html')->find('img')->attrs('src');
        //打印结果
        print_r($data->all());
    }

    public function rouqilei(){
        $this->url = 'https://www.meishichina.com/YuanLiao/category/rql/';
        $this->rule = array(
            $this->bigCategory = array('body > div.wrap > div > div > div > h3','text'),
            $this->smallCategory = array('body > div.wrap > div > div > div > ul > li','text'),
        );
        $hj = QueryList::Query($this->url,$this->rule);
        $data = $hj->getData(function($item){
            return $item;
        });
        print_r($data);
    }

}