<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/12
 * Time: 22:31
 */


namespace app\index\controller;

use app\common\controller\Frontend;
use think\Lang;
use think\Db;
use QL\QueryList;
use think\Log;

/**
 * Ajax异步请求接口
 * @internal
 */
class Caiji
{
    private $parent_id = 0;
    private $last_id = 0;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function meet(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/rql/';
        $data = [];
        //猪肉分类
        $data['zhurou'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //牛肉分类
        $data['niurou'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //鸡肉分类
        $data['jirou'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //羊肉分类
        $data['yangrou'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //蛋类
        $data['yangrou'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其它肉类
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');
        //其它禽类
        $data['other_qinlei'] = QueryList::get($url)->find('div.category_sub:nth-child(7) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function shuichanpin(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/scl/';
        $data = [];
        //淡水鱼
        $data['danshuiyu'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //海水鱼
        $data['haishuiyu'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //虾类
        $data['xia'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //蟹类
        $data['xie'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //贝类
        $data['bei'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其他水产类
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function shucai(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/shucailei/';
        $data = [];
        //茎叶类
        $data['jingye'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //瓜菜类
        $data['guacai'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //果实类
        $data['guoshi'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //根茎类
        $data['genjing'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //菌类
        $data['jun'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //其他
        $data['other'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '采集分类成功';
                    }
                }

            }
        }
    }

    public function guopin(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/guopinlei/';
        $data = [];
        //鲜果类
        $data['xianguo'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //干果类
        $data['ganguo'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function mimian(){
        //采集某页面所有的图片
        $url = 'https://www.meishichina.com/YuanLiao/category/mmdr/';
        $data = [];
        //米类
        $data['mi'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //面类
        $data['mian'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //豆类
        $data['dou'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //豆制品
        $data['douzhipin'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //乳类
        $data['ru'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //方便食品类
        $data['fangbian'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function tiaoweipin(){
        $url = 'https://www.meishichina.com/YuanLiao/category/tiaoweipinl/';
        $data = [];
        //调味品
        $data['tiaoweipin'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //食用油
        $data['shiyongyou'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function yaoshi(){
        $url = 'https://www.meishichina.com/YuanLiao/category/yaoshiqita/';
        $data = [];
        //药食
        $data['tiaoweipin'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('shicai_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkShiCaiCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('shicai_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function food_category(){
        $url = 'https://home.meishichina.com/recipe-type.html';
        $data = [];
        //常见菜式
        $data['jiachangcai'] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //主食/小吃
        $data['xiaochi'] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //甜品/饮品
        $data['tianpin'] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //适宜人群
        $data['tianpin'] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //食疗食补
        $data['shibu'] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //场景
        $data['changjing'] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');
        //饮食方式
        $data['yingshi'] = QueryList::get($url)->find('div.category_sub:nth-child(7) > ul > li > a')->attrs('title');
        //中式菜式
        $data['china'] = QueryList::get($url)->find('div.category_sub:nth-child(8) > ul > li > a')->attrs('title');
        //外国美食
        $data['world'] = QueryList::get($url)->find('div.category_sub:nth-child(9) > ul > li > a')->attrs('title');
        //烘焙
        $data['hongpei'] = QueryList::get($url)->find('div.category_sub:nth-child(10) > ul > li > a')->attrs('title');
        //传统美食
        $data['chuantong'] = QueryList::get($url)->find('div.category_sub:nth-child(11) > ul > li > a')->attrs('title');
        //节日食俗
        $data['jieri'] = QueryList::get($url)->find('div.category_sub:nth-child(12) > ul > li > a')->attrs('title');
        //按制作难度
        $data['hard'] = QueryList::get($url)->find('div.category_sub:nth-child(13) > ul > li > a')->attrs('html');
//        var_dump($data);exit;
        //按所需时间
        $data['time'] = QueryList::get($url)->find('div.category_sub:nth-child(14) > ul > li > a')->attrs('text');
        //按菜品口味
        $data['kouwei'] = QueryList::get($url)->find('div.category_sub:nth-child(15) > ul > li > a')->attrs('text');
        //按主要工艺
        $data['gongyi'] = QueryList::get($url)->find('div.category_sub:nth-child(16) > ul > li > a')->attrs('text');

        $url = file_get_contents('https://home.meishichina.com/recipe-type.html');

        $temp = [];
        foreach($data as $key => $value){
            foreach($value as $k => $v){

                if ($k == 0){
                    $result = self::_checkFoodCategory($v);
                    $temp['parent_id'] = 0;
                    $temp['food_category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('food_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        $this->parent_id = db::name('food_category')->getLastInsID();
                    }
                }else{
                    $result = self::_checkFoodCategory($v);
                    $temp['parent_id'] = $this->parent_id;
                    $temp['food_category_name'] = $v;
                    $temp['create_time'] = date('Y-m-d H:i:s');
                    $temp['update_time'] = date('Y-m-d H:i:s');
                    if ($result){
                        $res = Db::name('food_category')->insert($temp);
                    }else{
                        $res = false;
                    }
                    if ($res){
                        echo '.';
                    }
                }

            }
        }
    }

    public function shiliao_category(){
        $url = 'https://www.meishichina.com/YuanLiao/gongxiao/';
        $data = [];
        //养生保健
        $data[0] = QueryList::get($url)->find('div.category_sub:nth-child(1) > ul > li > a')->attrs('title');
        //美容减肥
        $data[1] = QueryList::get($url)->find('div.category_sub:nth-child(2) > ul > li > a')->attrs('title');
        //男性
        $data[2] = QueryList::get($url)->find('div.category_sub:nth-child(3) > ul > li > a')->attrs('title');
        //女性
        $data[3] = QueryList::get($url)->find('div.category_sub:nth-child(4) > ul > li > a')->attrs('title');
        //孕前哺乳
        $data[4] = QueryList::get($url)->find('div.category_sub:nth-child(5) > ul > li > a')->attrs('title');
        //神经系统
        $data[5] = QueryList::get($url)->find('div.category_sub:nth-child(6) > ul > li > a')->attrs('title');
        //呼吸道
        $data[6] = QueryList::get($url)->find('div.category_sub:nth-child(7) > ul > li > a')->attrs('title');
        //心血管
        $data[7] = QueryList::get($url)->find('div.category_sub:nth-child(8) > ul > li > a')->attrs('title');
        //肝胆脾胰
        $data[8] = QueryList::get($url)->find('div.category_sub:nth-child(9) > ul > li > a')->attrs('title');
        //五官
        $data[9] = QueryList::get($url)->find('div.category_sub:nth-child(10) > ul > li > a')->attrs('title');
        //肌肉骨骼
        $data[10] = QueryList::get($url)->find('div.category_sub:nth-child(11) > ul > li > a')->attrs('title');
        //癌症
        $data[11] = QueryList::get($url)->find('div.category_sub:nth-child(12) > ul > li > a')->attrs('title');
        //其他
        $data[12] = QueryList::get($url)->find('div.category_sub:nth-child(13) > ul > li > a')->attrs('title');

        $url = file_get_contents($url);
        $title = QueryList::rules(array(
            'big_category' => array('body > div.wrap > div > div.category_box.mt20 > div > h3','text'),
        ));
        $data1 = $title->setHtml($url)->removeHead()->query()->getData();
//        var_dump($data1);
//        var_dump($data);

        $temp = [];
        foreach($data as $key => $value){
            $r = self::_checkHealthCategory($data1[$key]['big_category']);
            if ($r){
                $tmp['parent_id'] = 0;
                $tmp['health_category_name'] = $data1[$key]['big_category'];
                $tmp['create_time'] = date('Y-m-d H:i:s');
                $tmp['update_time'] = date('Y-m-d H:i:s');
                $res = Db::name('health_category')->insert($tmp);
                echo Db::name('health_category')->getLastSql();
                if ($res){
                    $this->parent_id = Db::name('health_category')->getLastInsID();
                }else{

                }
            }
            foreach($value as $k => $v){
                $result = self::_checkHealthCategory($v);
                $temp['parent_id'] = $this->parent_id;
                $temp['health_category_name'] = $v;
                $temp['create_time'] = date('Y-m-d H:i:s');
                $temp['update_time'] = date('Y-m-d H:i:s');
                if ($result){
                    $res = Db::name('health_category')->insert($temp);
                }else{
                    $res = false;
                }
                if ($res){
                    echo '.';
                }
            }
        }
    }


    public function recai(){
        $url = file_get_contents('https://home.meishichina.com/recipe/recai/');

        $ql = QueryList::rules(array(
            'food_name' => array('#J_list >ul > li >.detail > h2>a','text'),
            'food_url' => array('#J_list >ul > li >.detail > h2>a','href'),
            'tags' => array('#J_list >ul > li >.detail > p.subcontent','text'),
            'images' => array('#J_list > ul > li > div.pic > a > img','data-src'),
//            'author_name' => array('#J_list > ul > li > div.detail > p.subline > a','text'),
            'page' => array('.ui-page-inner .now_page','text'),
        ));
        $data = $ql->setHtml($url)->removeHead()->query()->getData();

        Db::startTrans();
        foreach($data as $key => $value){
            if ($key == 0){
                unset($value['page']);
            }
            $value['create_time'] = $value['update_time'] = date('Y-m-d H:i:s');
            $value['images'] = explode('?',$value['images'])[0];
            $res = Db::name('food_list')->insert($value);

            if (!$res){
                DB::rollback();
            }else{
                $html = file_get_contents($value['food_url']);
//                $html = file_get_contents('https://home.meishichina.com/recipe-151200.html');
//                $html = file_get_contents('https://home.meishichina.com/recipe-151106.html');
//                $html = file_get_contents('https://home.meishichina.com/recipe-181606.html');
                $data1['old_id'] = explode('.',explode('-',$value['food_url'])[1])[0];
                $food2 = QueryList::rules(array(
                    'space_id' => array('body > div.wrap > div > div.space_left > div.space_box_home > div > div > a','href')
                ));
                $data3 = $food2->setHtml($html)->removeHead()->query()->getData();

                $food1 = QueryList::rules(array(
                    'tips' => array('.recipeTip','text'),
                ));
                $data2 = $food1->setHtml($html)->removeHead()->query()->getData();
                $length = count($data2);
                $food1->destruct();

                $food = QueryList::rules(array(
                    'food_name' => array('#recipe_title','text'),
                    'descrpition' => array('#block_txt1','text'),
                    'top_image' => array('#recipe_De_imgBox > a > img','src'),
                    'main_material' => array('div.recipeCategory_sub_R.clear','html'),
                    'other_tags' => array('body > div.wrap > div > div.space_left > div.space_box_home > div > fieldset > div > ul','html'),
                    'assist_material' => array('div.recipeCategory_sub_R.mt30.clear','html'),
                    'images' => array('.recipeStep_img > img','src'),
                    'cooking_process' => array('.recipeStep_word','text'),
                ));

                $data = $food->setHtml($html)->removeHead()->query()->getData();

//                echo '<pre>';
//                print_r($data);exit;
                if (!isset($data[0]['food_name'])){
                    $data1['food_name'] = '';
                }else{
                    $data1['food_name']= htmlspecialchars($data[0]['food_name']);
                }

                if (!isset($data[0]['descrpition'])){
                    $data1['descrpition'] = '';
                }else{
                    $data1['descrpition'] = json_encode(htmlspecialchars($data[0]['descrpition']));
                }

                if (!isset($data[0]['top_image'])){
                    $data1['top_image'] = '';
                }else{
                    $data1['top_image'] = explode("?",$data[0]['top_image'])[0];
                }

                $count = count($data);
                for ($i = 0; $i < $count; $i++){
                    $data1['images'][$i] = explode('?',$data[$i]['images'])[0];
                    $data1['cooking_process'][$i] = $data[$i]['cooking_process'];
                }
                $data1['images'] = json_encode($data1['images']);
                $data1['cooking_process'] = json_encode($data1['cooking_process']);

                preg_match_all('/<b>(.+?)<\/b>/', $data[0]['main_material'], $tag1);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[0]['main_material'], $tag2);
                str_replace('<b>','',$tag1[1]);
                str_replace('</b>','',$tag1[1]);
                $main_material = array_combine($tag1[1],$tag2[1]);

                preg_match_all('/target="_blank">(.+?)<\/a>/', $data[0]['assist_material'], $tag3);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[0]['assist_material'], $tag4);
                str_replace('<b>','',$tag3[1]);
                str_replace('</b>','',$tag3[1]);
                $other_tags = array_combine($tag3[1],$tag4[1]);

                preg_match_all('/<b>(.+?)<\/b>/', $data[1]['other_tags'], $tag33);
                preg_match_all('/<span class="category_s2">(.+?)<\/span>/', $data[1]['other_tags'], $tag44);
                str_replace('<b>','',$tag33[1]);
                str_replace('</b>','',$tag33[1]);
                $assist_material= array_combine($tag33[1],$tag44[1]);

                $data1['main_material'] = json_encode($main_material);
                $data1['other_tags'] = json_encode($other_tags);
                $data1['assist_material'] = json_encode($assist_material);
                if ($length > 3){
                    $data1['tips'] = json_encode($data2[$length-4]['tips']);
                }

                $data1['space_id'] = explode('.',explode('-',$data3[1]['space_id'])[1])[0];
                $data1['kitchen_ware'] = explode('：',$data2[$length-2]['tips'])[1];
                $data1['big_category'] = explode('|',str_replace('&nbsp;&nbsp;','|', htmlentities(trim(explode('：',$data2[$length-1]['tips'])[1]))));
                foreach ($data1['big_category'] as $k => $v){
                        $data1['big_category'][$k] = trim($v);
                }
                $count = count($data1['big_category']);
                unset($data1['big_category'][$count-1]);
                $big_category = $data1['big_category'];
                unset($data1['big_category']);

                $data1['create_time'] = date('Y-m-d H:i:s');
                $data1['update_time'] = date('Y-m-d H:i:s');

                $old = Db::name('food')->where('old_id='.$data1['old_id'])->find();
                if (!$old){
                    $res = Db::name('food')->insert($data1);
                    $this->last_id = Db::name('food')->getLastInsID();
                    $main_material = json_decode($data1['main_material']);
                    foreach ($main_material as $key => $value){
                        $r = Db::name('shicai_category')->where('category_name="'.$key.'"')->find();
                        if ($r) {
                            $shicai_category1[] = $r['category_id'];
                        }
                    }
                    $assist_material = json_decode($data1['assist_material']);
                    foreach ($assist_material as $key => $value){
                        $r = Db::name('shicai_category')->where('category_name="'.$key.'"')->find();
                        if ($r) {
                            $shicai_category2[] = $r['category_id'];
                        }
                    }
//                    echo Db::name('shicai_category')->getLastSql();exit;
                    $other_tags = json_decode($data1['other_tags']);
                    foreach ($other_tags as $key => $value){
                        echo $key;
                        $r = Db::name('food_category')->where('food_category_name="'.$key.'"')->find();
                        if ($r) {
                            $food_category[] = $r['food_category_id'];
                        }
                    }
//                    var_dump($shicai_category1);
//                    var_dump($shicai_category2);
//                    var_dump($food_category);exit;
                    if (!empty($shicai_category1)){
                        foreach ($shicai_category1 as $value){
                            $where1['shicai_category_id'] = $value;
                            $where1['food_id'] = $this->last_id ;
                            $s = Db::name('shicai_category_relation')->where($where1)->find();
                            echo Db::name('shicai_category_relation')->getLastSql();
                            if (!$s){
                                $where1['create_time'] = $where1['update_time'] =date('Y-m-d H:i:s');
                                $t = Db::name('shicai_category_relation')->insert($where1);
                                if (!$t){
                                    Log::record('菜谱'.$where1['food_id'].'分类'.$where1['shicai_category_id'].'没有创建','error');
                                }
                                unset($where1);
                            }
                        }
                    }

                }else{
                    continue;
                }

                if (!$res){
                    Db::rollback();
                }else{
                    foreach ($big_category as $value){
                        $where['food_category_name'] = $value;
                        $food_category = Db::name('food_category')->where($where)->find();
//                        echo db::name('food_category')->getLastSql();
                        $ralation = array();
                        if ($food_category['food_category_id'] > 0){
                            $ralation['food_category_id'] = $food_category['food_category_id'];
                            $ralation['good_id'] = $this->last_id;
                            $ralation['create_time'] = date('Y-m-d H:i:s');
                            $ralation['update_time'] = date('Y-m-d H:i:s');
                            $res = Db::name('food_category_relation')->insert($ralation);
                            if ($res){
                                Db::commit();
                                unset($data1);
                            }else{
                                Db::rollback();
                            }
                        }
                    }
                }
            }
        }
    }

    private static function _checkShiCaiCategory($category){
        $res = Db::name('shicai_category')->where('category_name="'.$category.'"')->find();
//        echo Db::name('shicai_category')->getLastSql();exit;
        if ($res){
            return false;
        }else{
            return true;
        }
    }

    private static function _checkFoodCategory($category){
        $res = Db::name('food_category')->where('food_category_name="'.$category.'"')->find();
        if ($res){
            return false;
        }else{
            return true;
        }
    }

    private static function _checkHealthCategory($category){
        $res = Db::name('health_category')->where('health_category_name="'.$category.'"')->find();
        if ($res){
            return false;
        }else{
            return true;
        }
    }

    public function order_list(){
        $page = input('page/d');
        $pageSize = 4;
        $list = Db::name('food')->field('food_id,food_name,update_time')->select();
        $count = Db::name('food')->field('food_id,food_name,update_time')->count();
        $day = '';
        foreach ($list as $key => $value){
            if ($key == 0){
                $day = isset($list[0]['update_time']) ? date('Y-m-d',strtotime($list[0]['update_time'])) : '';
                array_unshift($list[0],$day);
            }
            if ($day != date('Y-m-d',strtotime($value['update_time']))){
//                echo date('Y-m-d',strtotime($value['update_time']));
                $day = date('Y-m-d',strtotime($value['update_time']));
                array_unshift($list[$key],$day);
            }
        }
//        array_unshift($list,$day);
//        var_dump($list);
        echo count($list);exit;

        foreach($list as $key => $value){
            if (isset($value[0])){
                echo $value[0];
            }

        }
    }
}