<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/2
 * Time: 23:29
 */

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Log;

class Category extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function foodCategory(){
        $categoryId = input('category/d',0);
        $list = array();
        if ($categoryId > 0){
            $list = Db::name('food_list')
                ->alias('a')
                ->join('food_category_relation b','a.food_id = b.food_id and a.status = 1')
                ->where('b.food_category_id ='.$categoryId)
                ->paginate(10);
        }else{

        }

        $this->assign('foodlist',$list);
        return $this->fetch();
    }

}

