<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/2
 * Time: 23:29
 */

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Log;
use think\Route;

class Food extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function food(){
        $foodId = input('food_id/d',0);
        $page = input('page/d',1);
        $pageSize = 10;
        if ($foodId > 0){
            $food = Db::name('food')
                ->where('food_id ='.$foodId)
                ->page($page,$pageSize)
                ->find();
//            var_dump($list);
            $food['descrpition'] = json_decode($food['descrpition']);
            $food['images'] = ltrim($food['images'],"'[");
            $food['images'] = rtrim($food['images'],"]'");
            $food['images'] = str_replace('\/','/',$food['images']);
            $food['images'] = explode(',',$food['images']);
            $food['main_material'] = json_decode($food['main_material']);
            $food['assist_material'] = json_decode($food['assist_material']);
            $food['mix_material'] = json_decode($food['mix_material']);
            $food['other_tags'] = json_decode($food['other_tags']);
            $food['cooking_process'] = json_decode($food['cooking_process']);
            $food['tips'] = json_decode($food['tips']);

//            $food['main_material'] = json_decode($food['main_material']);
        }else{
            Log::error('菜谱里面什么都没有');
        }
        foreach ($food['images'] as $key => &$value){
            $value = str_replace('"','',$value);
        }
        if (!empty($food['main_material'])){
            foreach($food['main_material'] as $key => $value){
                $category = Db::name('shicai_category')->field('category_id')->where('category_name = '.'"'.$key.'"')->find();
                $url = url('index/Category/foodCategory',['category'=>$category['category_id']]);
                $key = '<a href="/index.php'.$url.'">'.$key.'</a>';
                $temp1[$key] = $value;
            }
            $food['main_material_url'] = $temp1;
        }

        if (!empty($food['assist_material'])) {
            foreach ($food['assist_material'] as $key => $value) {
                $category = Db::name('shicai_category')->field('category_id')->where('category_name = ' . '"' . $key . '"')->find();
                $url = url('index/Category/foodCategory', ['category' => $category['category_id']]);
                $key = '<a href="/index.php' . $url . '">' . $key . '</a>';
                $temp2[$key] = $value;
            }
            $food['assist_material_url'] = $temp2;
        }

        if (!empty($food['mix_material'])) {
            foreach ($food['mix_material'] as $key => $value) {
                $category = Db::name('shicai_category')->field('category_id')->where('category_name = ' . '"' . $key . '"')->find();
                $url = url('index/Category/foodCategory', ['category' => $category['category_id']]);
                $key = '<a href="/index.php' . $url . '">' . $key . '</a>';
                $temp3[$key] = $value;
            }
            $food['mix_material_url'] = $temp3;
        }
        if (!empty($food['other_tags'])) {
            foreach ($food['other_tags'] as $key => $value) {

                $category = Db::name('shicai_category')->field('category_id')->where('category_name = ' . '"' . $key . '"')->find();
                $url = url('index/Category/foodCategory', ['category' => $category['category_id']]);
                $key = '<a href="/index.php' . $url . '">' . $key . '</a>';
                $temp4[$key] = $value;
            }
            $food['other_tags_url'] = $temp4;
        }

        $category = Db::name('food_category')->alias('a')
            ->join('food_category_relation b','a.food_category_id = b.food_category_id')
            ->where('b.food_id ='.$food['food_id'].' and a.type = 1')
            ->select();
        var_dump($food);
        $this->assign('page',$page);
        $this->assign('food',$food);
        $this->assign('category',$category);
        return $this->fetch();

    }


}